package Vista;

import Modelo.Conexion;
import Modelo.GenerarPdf;
import Modelo.Validable;
import javax.swing.JOptionPane;

import java.awt.Color;
import java.util.List;
import javax.swing.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author marvin
 */
public class Comprar extends javax.swing.JFrame implements Validable{

    private String idVuelo;

    private Comprar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean validarCampos(List<JComponent> campos)
    {
        for (JComponent campo : campos) {
            if (campo instanceof JTextField) {
                JTextField textField = (JTextField) campo;
                if (textField.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos obligatorios.", "Error", JOptionPane.WARNING_MESSAGE);
                    return false;
                }
            } else if (campo instanceof JComboBox) {
                JComboBox<?> comboBox = (JComboBox<?>) campo;
                if (comboBox.getSelectedIndex() == 0) { // Verificar que no esté en "Seleccione una opción"
                    JOptionPane.showMessageDialog(this, "Por favor, selecciona una opción válida.", "Error", JOptionPane.WARNING_MESSAGE);
                    return false;
                }
            } else if (campo instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) campo;
                if (!checkBox.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Por favor, confirma los términos y condiciones.", "Error", JOptionPane.WARNING_MESSAGE);
                    return false;
                }
            }
        }
        return true;
    }
    /**
     * Creates new form Comprar
     */
    public Comprar(String idVuelo, String origen, String destino, String fechaSalida, String horaSalida, String precio) {
        initComponents();
        this.idVuelo=idVuelo;
        this.setLocationRelativeTo(null);
        
        // Rellenar los campos con los datos recibidos
        origenV1.setText(origen);
        destinoV1.setText(destino);
        fechaV1.setText(fechaSalida);
        horaV1.setText(horaSalida);
        precioV1.setText(precio);
        
        origenV1.setEditable(false);
        destinoV1.setEditable(false);
        fechaV1.setEditable(false);
        horaV1.setEditable(false);
        precioV1.setEditable(false);
        
        // Cambiar el color de fondo a #00CC33
        Color colorVerde = new Color(0x00CC33);
        origenV1.setBackground(colorVerde);
        destinoV1.setBackground(colorVerde);
        fechaV1.setBackground(colorVerde);
        horaV1.setBackground(colorVerde);
        precioV1.setBackground(colorVerde);

        // Cambiar el color de texto (opcional, para contraste)
        origenV1.setForeground(Color.WHITE);
        destinoV1.setForeground(Color.WHITE);
        fechaV1.setForeground(Color.WHITE);
        horaV1.setForeground(Color.WHITE);
        precioV1.setForeground(Color.WHITE);
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        origenV1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        destinoV1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechaV1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        horaV1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        precioV1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nombreCli = new javax.swing.JTextField();
        apellidoCli = new javax.swing.JTextField();
        emailCli = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telefonoCli = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rfcCli = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        asiento = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        clase = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentarios = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        metpago = new javax.swing.JComboBox<>();
        checkbox1 = new java.awt.Checkbox();
        jLabel23 = new javax.swing.JLabel();
        digitos = new javax.swing.JTextField();
        bcomprarvuelo = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        jLabel18.setText("jLabel18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 1, 18)); // NOI18N
        jLabel1.setText("Detalles del Vuelo");

        jLabel4.setFont(new java.awt.Font("Jaini Purva", 1, 14)); // NOI18N
        jLabel4.setText("Origen");

        jLabel5.setText("Destino");

        destinoV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoV1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de Salida");

        jLabel7.setText("Hora de Salida");

        jLabel9.setFont(new java.awt.Font("Jaini Purva", 1, 14)); // NOI18N
        jLabel9.setText("Precio");

        jLabel2.setText("Ingrese los Siguientes Datos...");

        jLabel3.setFont(new java.awt.Font("Lava Kannada", 1, 18)); // NOI18N
        jLabel3.setText("Detalles del Cliente");

        jLabel8.setText("Nombre");

        jLabel10.setText("Apellido");

        jLabel11.setText("Email");

        apellidoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoCliActionPerformed(evt);
            }
        });

        emailCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCliActionPerformed(evt);
            }
        });

        jLabel13.setText("Teléfono");

        jLabel14.setText("RFC (opcional)");

        rfcCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfcCliActionPerformed(evt);
            }
        });

        jLabel15.setText("MXN");

        jLabel16.setFont(new java.awt.Font("Lava Kannada", 1, 18)); // NOI18N
        jLabel16.setText("Preferencias");

        jLabel17.setText("Asiento");

        asiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "ventana", "pasillo", "centro" }));
        asiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asientoActionPerformed(evt);
            }
        });

        jLabel19.setText("Clase de Vuelo");

        clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "económica", "bussines", "primera clase" }));

        jLabel20.setText("Comentarios Adicioneles");

        comentarios.setColumns(20);
        comentarios.setRows(5);
        jScrollPane1.setViewportView(comentarios);

        jLabel21.setFont(new java.awt.Font("Lava Kannada", 1, 18)); // NOI18N
        jLabel21.setText("Sección de Pago");

        jLabel22.setText("Método de Pago");

        metpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opción...", "efectivo", "tarjeta", "transferencia" }));

        checkbox1.setLabel("Confirmo que he revisado los detalles de mi vuelo y acepto los términos y condiciones.");

        jLabel23.setText("Ultimos 4 digitos");

        digitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitosActionPerformed(evt);
            }
        });

        bcomprarvuelo.setText("Comprar Vuelo");
        bcomprarvuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcomprarvueloActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel5)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(origenV1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(destinoV1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaV1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(horaV1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(precioV1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabel19)))
                        .addGap(133, 133, 133)
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreCli, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel13)
                                .addGap(135, 135, 135)
                                .addComponent(jLabel14)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emailCli, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telefonoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rfcCli, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(metpago, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(digitos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(asiento, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bcomprarvuelo)
                                .addGap(80, 80, 80))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCancelar)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinoV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rfcCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(digitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcomprarvuelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destinoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoV1ActionPerformed

    private void apellidoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoCliActionPerformed

    private void emailCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCliActionPerformed

    private void rfcCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfcCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfcCliActionPerformed

    private void asientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asientoActionPerformed

    private void digitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digitosActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        VenderVuelo frmLogin = new VenderVuelo();
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bcomprarvueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcomprarvueloActionPerformed
        List<JComponent> camposObligatorios = List.of(
        nombreCli,
        apellidoCli,
        emailCli,
        telefonoCli,
        asiento,
        clase,
        metpago
        );
        
        if(!validarCampos(camposObligatorios))
        {
            return;
        }
        if (!checkbox1.getState()) { // Verificar si no está seleccionado
            JOptionPane.showMessageDialog(this, "Por favor, confirma los términos y condiciones.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //datos del cliente
        String nombre = nombreCli.getText();
        String apellido = apellidoCli.getText();
        String email = emailCli.getText();
        String telefono= telefonoCli.getText();
        String rfc= rfcCli.getText().isEmpty() ? null : rfcCli.getText();
        
        //datos de la reservacion
        String asientoSeleccionado = asiento.getSelectedItem().toString();
        String claseSeleccionada =clase.getSelectedItem().toString();
        String comentariosAdicionales = comentarios.getText();
        String metodoPago= metpago.getSelectedItem().toString();
        String ultimosDigitos = digitos.getText().isEmpty() ? null : digitos.getText();
        
        //detalles del vuelo
        /*String origen = origenV1.getText();
        String destino = destinoV1.getText();
        String fechaSalida = fechaV1.getText();
        String horaSalida = horaV1.getText();*/
        double precio = Double.parseDouble(precioV1.getText());
        
        try (Connection conn = Conexion.getConnection()) {
            if (conn == null) {
                throw new SQLException("No se pudo establecer la conexión a la base de datos.");
            }
            conn.setAutoCommit(false);

            int idUsuario;
            String buscarUsuarioSQL = "SELECT id_usuario FROM Usuarios WHERE email = ?";
            try (PreparedStatement buscarUsuarioStmt = conn.prepareStatement(buscarUsuarioSQL)) {
                buscarUsuarioStmt.setString(1, email);
                try (ResultSet rs = buscarUsuarioStmt.executeQuery()) {
                    if (rs.next()) {
                        idUsuario = rs.getInt("id_usuario");
                    } else {
                        String insertarUsuarioSQL = "INSERT INTO Usuarios (nombre, apellido, email, telefono, rfc, tipoUsuario) VALUES (?, ?, ?, ?, ?, 'cliente')";
                        try (PreparedStatement insertarUsuarioStmt = conn.prepareStatement(insertarUsuarioSQL, Statement.RETURN_GENERATED_KEYS)) {
                            insertarUsuarioStmt.setString(1, nombre);
                            insertarUsuarioStmt.setString(2, apellido);
                            insertarUsuarioStmt.setString(3, email);
                            insertarUsuarioStmt.setString(4, telefono);
                            insertarUsuarioStmt.setString(5, rfc);
                            insertarUsuarioStmt.executeUpdate();
                            try (ResultSet generatedKeys = insertarUsuarioStmt.getGeneratedKeys()) {
                                if (generatedKeys.next()) {
                                    idUsuario = generatedKeys.getInt(1);
                                } else {
                                    throw new SQLException("Error al crear el usuario.");
                                }
                            }
                        }
                    }
                }
            }

            String insertarReservacionSQL = "INSERT INTO Reservaciones (r_usuario, r_vuelo, fecha_reservacion, estado) VALUES (?, ?, NOW(), 'confirmada')";
            int idReservacion;
            try (PreparedStatement insertarReservacionStmt = conn.prepareStatement(insertarReservacionSQL, Statement.RETURN_GENERATED_KEYS)) {
                insertarReservacionStmt.setInt(1, idUsuario);
                insertarReservacionStmt.setInt(2, Integer.parseInt(idVuelo));
                insertarReservacionStmt.executeUpdate();
                try (ResultSet reservacionKeys = insertarReservacionStmt.getGeneratedKeys()) {
                    if (reservacionKeys.next()) {
                        idReservacion = reservacionKeys.getInt(1);
                    } else {
                        throw new SQLException("Error al crear la reservación.");
                    }
                }
            }

            String insertarPagoSQL = "INSERT INTO Pagos (r_reservacion, monto, metodoPago) VALUES (?, ?, ?)";
            try (PreparedStatement insertarPagoStmt = conn.prepareStatement(insertarPagoSQL)) {
                insertarPagoStmt.setInt(1, idReservacion);
                insertarPagoStmt.setDouble(2, precio);
                insertarPagoStmt.setString(3, metodoPago);
                insertarPagoStmt.executeUpdate();
            }

            conn.commit();
            
            GenerarPdf generador = new GenerarPdf();
            String rutaEscritorio = System.getProperty("user.home") + "/Desktop"; // Ruta al escritorio
            String rutaArchivo = rutaEscritorio + "/ticket_compra.pdf"; // Ruta donde se guardará el PDF
            String cliente = nombreCli.getText() + " " + apellidoCli.getText();
            String vuelo = origenV1.getText() + " a " + destinoV1.getText();
            double precioVuelo;
            try {
                precio = Double.parseDouble(precioV1.getText().replace(",", "").trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El precio no es válido. Por favor verifica los datos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String asientoSelec = asiento.getSelectedItem().toString();
            String claseSelec = clase.getSelectedItem().toString();
            
            generador.generarTicketCompra(rutaArchivo, cliente, vuelo, precio, asientoSelec, claseSelec);
            
            
            JOptionPane.showMessageDialog(this, "Compra realizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            Sistema sistema = new Sistema();
            sistema.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al realizar la compra: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bcomprarvueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoCli;
    private javax.swing.JComboBox<String> asiento;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bcomprarvuelo;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JComboBox<String> clase;
    private javax.swing.JTextArea comentarios;
    private javax.swing.JTextField destinoV1;
    private javax.swing.JTextField digitos;
    private javax.swing.JTextField emailCli;
    private javax.swing.JTextField fechaV1;
    private javax.swing.JTextField horaV1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> metpago;
    private javax.swing.JTextField nombreCli;
    private javax.swing.JTextField origenV1;
    private javax.swing.JTextField precioV1;
    private javax.swing.JTextField rfcCli;
    private javax.swing.JTextField telefonoCli;
    // End of variables declaration//GEN-END:variables
}
