/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Conexion;
import javax.swing.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author marvin
 */
public class Promos extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    /**
     * Creates new form Promos
     */
    public Promos() {
        
        initComponents();
        cargarPromociones();
        this.setLocationRelativeTo(null);
        comprar.addActionListener(evt -> comprarPromocion());

    }
    
    private void cargarPromociones()
    {
        String sql = """
                     select Promociones.id_promocion, Promociones.descripcion,
                             Promociones.descuento, Promociones.fecha_inicio,
                             Promociones.fecha_fin, Promociones.condiciones,
                             Vuelos.origen, Vuelos.destino, Vuelos.fechaSalida, Vuelos.horaSalida, Vuelos.precio
                     from Promociones
                     join Vuelos
                     on Promociones.r_vuelo = Vuelos.id_vuelo""";
        
        try (Connection con = Conexion.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {

           DefaultTableModel model = new DefaultTableModel();
           model.addColumn("ID Promoción");
           model.addColumn("Descripción");
           model.addColumn("Descuento (%)");
           model.addColumn("Fecha Inicio");
           model.addColumn("Fecha Fin");
           model.addColumn("Origen");
           model.addColumn("Destino");
           model.addColumn("Fecha de Salida");
            model.addColumn("Hora de Salida");
           model.addColumn("Precio Original");
           model.addColumn("Precio con Descuento");

           while (rs.next()) {
               double precio = rs.getDouble("precio");
               double descuento = rs.getDouble("descuento");
               double precioConDescuento = precio - (precio * descuento / 100);

               model.addRow(new Object[]{
                   rs.getInt("id_promocion"),
                   rs.getString("descripcion"),
                   rs.getDouble("descuento"),
                   rs.getDate("fecha_inicio"),
                   rs.getDate("fecha_fin"),
                   rs.getString("origen"),
                   rs.getString("destino"),
                   rs.getDate("fechaSalida"),
                   rs.getString("horaSalida"),
                   precio,
                   String.format("%.2f", precioConDescuento)
               });
           }

           tablaPromos.setModel(model);

       } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, "Error al cargar las promociones: " + e.getMessage());
       }
    }
    
    private void comprarPromocion()
    {
        // Obtener la fila seleccionada
        int selectedRow = tablaPromos.getSelectedRow();
        if (selectedRow >= 0) {
            // Obtener los valores de la fila seleccionada
            String idVuelo = tablaPromos.getValueAt(selectedRow, 0).toString(); // Asumiendo que ID Vuelo está en la primera columna
            String origen = tablaPromos.getValueAt(selectedRow, 5).toString(); // Columna del origen
            String destino = tablaPromos.getValueAt(selectedRow, 6).toString(); // Columna del destino
            String fechaSalida = tablaPromos.getValueAt(selectedRow, 7).toString(); // Columna de fecha de salida
            String horaSalida = tablaPromos.getValueAt(selectedRow, 8).toString(); // Columna de hora de salida
            String precio = tablaPromos.getValueAt(selectedRow, 10).toString(); // Columna del precio con descuento

            // Crear y abrir el JFrame "Comprar"
            Comprar comprarFrame = new Comprar(idVuelo, origen, destino, fechaSalida, horaSalida, precio);
            comprarFrame.setVisible(true);

            // Cerrar el JFrame actual (opcional)
            this.dispose();
        } else {
            // Mostrar un mensaje si no se seleccionó ninguna fila
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una promoción.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        comprar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPromos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Promociones Disponibles");

        atras.setBackground(new java.awt.Color(0, 153, 0));
        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        comprar.setBackground(new java.awt.Color(0, 153, 51));
        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        tablaPromos.setBackground(new java.awt.Color(0, 204, 102));
        tablaPromos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPromos.setBounds(new java.awt.Rectangle(0, 0, 892, 400));
        tablaPromos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tablaPromos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(atras)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comprar)
                        .addGap(60, 60, 60))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(atras)))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(comprar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        Sistema fSis = new Sistema();
        fSis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        comprarPromocion();
    }//GEN-LAST:event_comprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Promos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton comprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaPromos;
    // End of variables declaration//GEN-END:variables
}
